export const V1HubFunctionNames = {
    'checkSendLimit': null,
    'deployedAt': null,
    'divisor': null,
    'inflate': null,
    'inflation': null,
    'initialIssuance': null,
    'issuance': null,
    'issuanceByStep': null,
    'limits': null,
    'name': null,
    'organizationSignup': null,
    'organizations': null,
    'period': null,
    'periods': null,
    'pow': null,
    'seen': null,
    'signup': null,
    'signupBonus': null,
    'symbol': null,
    'timeout': null,
    'tokenToUser': null,
    'transferThrough': null,
    'trust': null,
    'userToToken': null,
    'validation': null,
    
}
export type V1HubFunctionName = keyof typeof V1HubFunctionNames;

