export const V1TokenFunctionNames = {
    'allowance': null,
    'approve': null,
    'balanceOf': null,
    'currentIssuance': null,
    'decimals': null,
    'decreaseAllowance': null,
    'findInflationOffset': null,
    'hub': null,
    'hubDeployedAt': null,
    'hubTransfer': null,
    'increaseAllowance': null,
    'inflationOffset': null,
    'lastTouched': null,
    'look': null,
    'name': null,
    'owner': null,
    'period': null,
    'periods': null,
    'periodsWhenLastTouched': null,
    'stop': null,
    'stopped': null,
    'symbol': null,
    'time': null,
    'timeout': null,
    'totalSupply': null,
    'transfer': null,
    'transferFrom': null,
    'update': null,
    
}
export type V1TokenFunctionName = keyof typeof V1TokenFunctionNames;

