name: Build SDK Workflow

on:
  push:
    branches: [ 20240215-examples ]
  pull_request:
    branches: [ 20240215-examples ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 20240215-examples

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build Contracts & SDK
        run: |
          ./buildContracts.sh
          npm i
          npm run build

      - name: Build example app
        run: |
          cd examples/svelte-playground
          npm i
          npm run build
