name: Build SDK Workflow

on:
  push:
    branches: [ 20240215-examples ]
  pull_request:
    branches: [ 20240215-examples ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 20240215-examples

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21' # Adjust this to your project's Node.js version

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build Contracts
        run: |
          ./buildContracts.sh
          npm i

      - name: Build SDK
        run: |
          npm run build
