name: Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 20240215-examples

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build Contracts & SDK
        run: |
          echo "Building contracts and SDK"
          ./buildContracts.sh
          npm i
          npm run build

      - name: Build example app
        run: |
          cd examples/svelte-playground
          npm i
          cp .env.example .env
          npm run build
